name : test

on: [push] 

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: 파이썬 설치
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: 파이썬 패키치 설치
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: 테스트 실행
              run: pytest

        
